<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Delete' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Profile' => '',
    'Reset' => '',
    'Search' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'Update' => '',
    'Users' => '',
    'Авторизация' => 'Prisijungimas',
    'Добавить пользователя' => '',
    'Добавить пользоветеля' => '',
    'Женщина' => '',
    'Опубликовано' => '',
    'Поля контента' => '',
    'Редактирование профиля' => '',
    'Редактировать' => '',
    'Сертификаты' => 'Sertifikatai',
    'Слайдер' => '',
    'Создать страницу' => 'Sukurti puslapį',
    'Удалено' => '',
    'Черновик' => '',
    'пароль' => 'Slaptžodis',
    'пользователь' => 'Prisijungimo vardas',
    'Sign In' => 'Prisijungimas',
    'Sign me in' => 'Prisijungti',
    'Toggle navigation' => 'Perjungti navigaciją',
    'Аккаунт' => 'Paskyra',
    'Главная' => 'Pagrindinis puslapis',
    'Добавить новость' => 'Pridėti naujeną',
    'Заказы ' => 'Užsakymai ',
    'История заказов' => 'Užsakymų istorija',
    'Категории' => 'Kategorijos',
    'Магазин' => 'Parduotuvė',
    'Маркетинг' => 'Marketingas',
    'Мужчина' => 'Vyras',
    'На главную сайта' => 'Atidaryti pagrindinį puslapį',
    'Настройки' => 'Nustatymai',
    'Настройки сайта' => 'Svetainės nustatymai',
    'Новости' => 'Naujienos',
    'Новый пароль' => 'Naujas slaptažodis',
    'Новый пароль еще раз' => 'Naujas slaptažodis dar kartą',
    'Пользователи' => 'Naudotojai',
    'Поля заказа' => 'Užsakymo laukai',
    'Производители' => 'Gamintojai',
    'Промокоды' => 'Nuolaidų kodai',
    'Сайт' => 'Svetainė',
    'Статус' => 'Būsena',
    'Страницы' => 'Puslapiai',
    'Типы доставки' => 'Pristatymo būdai',
    'Типы оплаты' => 'Mokėjimo būdai',
    'Типы цен' => 'Kainų tipai',
    'Товары' => 'Prekės',
    'Фильтры' => 'Filtrai',
];
