<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Apie mus' => 'Apie mus',
    'Atsiliepimai' => 'Atsiliepimai',
    'Garantijos' => 'Garantijos',
    'Katalogas' => 'Katalogas',
    'Kategorijos' => 'Kategorijos',
    'Kontaktai' => 'Kontaktai',
    'Krepšelis' => 'Krepšelis',
    'Plačiau' => 'Plačiau',
    'Please contact us if you think this is a server error. Thank you.' => 'Jeigu menote, kad tai yra serverio klaida, prašome susisiekti su mumis.',
    'Pristatymas ir apmokėjimas' => 'Pristatymas ir apmokėjimas',
    'Recommended products' => 'Rekomenduojami produktai',
    'Straipsniai' => 'Straipsniai',
    'The above error occurred while the Web server was processing your request.' => 'Įvyko serverio informacijos duomenų apdorojimo kalida',
    'The requested category does not exist.' => 'Kategorija nerasta',
    'The requested product does not exist.' => 'Prekė nerasta',
];
